### PR TITLE
Add support for path prefix within buckets

### PR DESCRIPTION
**Pull request by big213**
Allows storing of source and cached images in the same bucket, but using a different directory. Usage:

```ts
import { createHandler } from "image-resizing";

export const img = functions.https.onRequest(createHandler({
  // Where the source images are located.
  // E.g. gs://s.example.com/uploads/image.jpg
  sourceBucket: "gs://s.example.com/uploads",

  // Where the transformed images needs to be stored.
  // E.g. gs://storage.example.com/cache/image__w_80,h_60.jpg
  cacheBucket: "gs://s.example.com/cache",
}));
```

### CODE REVIEW

**Comment by koistya** [comment]
@big213 thanks for the PR! I would just suggest to parse out the path prefix from the `sourceBucket`, `cacheBucket` parameters:

```js
export const img = functions.https.onRequest(createHandler({
  sourceBucket: "gs://s.example.com/uploads",
  cacheBucket: "gs://s.example.com/cache",
});
```
Internally, the path can be extracted by using a helper function:

```js
/**
 * Extracts folder name (prefix) from the bucket name.
 * 
 * @example
 *   parseBucket("gs://s.example.com")          => ["gs://s.example.com", ""]
 *   parseBucket("gs://s.example.com/")         => ["gs://s.example.com", ""]
 *   parseBucket("gs://s.example.com/uploads")  => ["gs://s.example.com", "uploads/"]
 *   parseBucket("gs://s.example.com/uploads/") => ["gs://s.example.com", "uploads/"]
 */
function parseBucket(value: string): [bucket: string, prefix: string] {
  const protocol = ((i: number) => i === -1
   ? "gs:"
   : value.substring(0, i + 1)
  )(value.indexOf("://"));

  if (protocol !== "gs:") {
    throw new Error("Only Google Storage buckets are supported at the moment.");
  }

  return ((i: number) => {
    return i === -1
      ? [value, ""]
      : [
          value.substring(0, i),
          ((x) => x && (x.endsWith("/") ? x : `${x}/`))(value.substring(i + 1))
        ]
  })(value.indexOf("/", protocol ? protocol.length + 2 : 0));
}

```

**Comment by big213** [comment]
@koistya Nice, yeah that is a good idea. I was too lazy to deal with the parsing before, but this will definitely make it even easier for the user. Copied and pasted that function into `parse.ts`, should be working now.

**Comment by big213** [comment]
Actually, I've made one minor modification just here. Changed `sourceBucket` to `sourceBucketPath`, and same for the other. Felt like this would be more accurate, since it is no longer a raw bucket name, and it could include the folder path now. Let me know what you think.

**Comment by koistya** [comment]
@big213 cool, thanks again! I just added unit tests and kept `sourceBucket`, `cacheBucket` options as a lightweight alternative to having more explicit options such as `sourceBucketName` + `sourceBucketPath`.

**Pull request merged**
